name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: laughedelic/gha-obsidian/actions/ci@main

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: laughedelic/gha-obsidian/actions/e2e@main

  e2e-test-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: laughedelic/gha-obsidian/actions/e2e@main
        with:
          mobile: "true"
